### ISSUE TITLE
run.sh not working on Mac OS X

### ISSUE THREAD

**Issue by azarezade** [sachinruk/deepschool.io#10]
It returns the following error:
`docker: invalid reference format: repository name must be lowercase.`

**Comment by sachinruk** [comment]
Would you like to create a pull request with that. Would be useful!

**Comment by azarezade** [comment]
I found the solution, the following worked for me on mac:
`docker run -d -p 9000:8888 -v "$(pwd)":/notebook sachinruk/ml_class`
dose it also works on linux?
