### ISSUE TITLE
deepschool.io Lesson 01 - PenalisedRegression - Solutions Cell 13 type error

### ISSUE THREAD

**Issue by JeremyHLee** [sachinruk/deepschool.io#5]
My Machine:
OS X Yosemite 10.10.5 16GB i7 

-----------
CELL 13:
-----------

import numpy as np
from scipy import sparse
from scipy import ndimage
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.linear_model import ARDRegression
import matplotlib.pyplot as plt

def _weights(x, dx=1, orig=0):
    x = np.ravel(x)
    floor_x = np.floor((x - orig) / dx)
    alpha = (x - orig - floor_x * dx) / dx
    return np.hstack((floor_x, floor_x + 1)), np.hstack((1 - alpha, alpha))

def _generate_center_coordinates(l_x):
    X, Y = np.mgrid[:l_x, :l_x].astype(np.float64)
    center = l_x / 2.
    X += 0.5 - center
    Y += 0.5 - center
    return X, Y

def build_projection_operator(l_x, n_dir):
    """ Compute the tomography design matrix.

    Parameters
    ----------

    l_x : int
        linear size of image array

    n_dir : int
        number of angles at which projections are acquired.

    Returns
    -------
    p : sparse matrix of shape (n_dir l_x, l_x**2)
    """
    X, Y = _generate_center_coordinates(l_x)
    angles = np.linspace(0, np.pi, n_dir, endpoint=False)
    data_inds, weights, camera_inds = [], [], []
    data_unravel_indices = np.arange(l_x ** 2)
    data_unravel_indices = np.hstack((data_unravel_indices,
                                      data_unravel_indices))
    for i, angle in enumerate(angles):
        Xrot = np.cos(angle) * X - np.sin(angle) * Y
        inds, w = _weights(Xrot, dx=1, orig=X.min())
        mask = np.logical_and(inds >= 0, inds < l_x)
        weights += list(w[mask])
        camera_inds += list(inds[mask] + i * l_x)
        data_inds += list(data_unravel_indices[mask])
    proj_operator = sparse.coo_matrix((weights, (camera_inds, data_inds)))
    return proj_operator

def generate_synthetic_data():
    """ Synthetic binary data """
    rs = np.random.RandomState(0)
    n_pts = 36.
    x, y = np.ogrid[0:l, 0:l]
    mask_outer = (x - l / 2) ** 2 + (y - l / 2) ** 2 < (l / 2) ** 2
    mask = np.zeros((l, l))
    points = l * rs.rand(2, n_pts)
    mask[(points[0]).astype(np.int), (points[1]).astype(np.int)] = 1
    mask = ndimage.gaussian_filter(mask, sigma=l / n_pts)
    res = np.logical_and(mask > mask.mean(), mask_outer)
    return res - ndimage.binary_erosion(res)

/root/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:42: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.

TypeError                                 Traceback (most recent call last)
<ipython-input-13-f87e14171ca2> in <module>()
      2 l = 128
      3 proj_operator = build_projection_operator(l, l / 7.)
----> 4 data = generate_synthetic_data()
      5 proj = proj_operator * data.ravel()[:, np.newaxis]
      6 proj += 0.15 * np.random.randn(*proj.shape)

<ipython-input-12-eba2b8716a3f> in generate_synthetic_data()
     63     mask_outer = (x - l / 2) ** 2 + (y - l / 2) ** 2 < (l / 2) ** 2
     64     mask = np.zeros((l, l))
---> 65     points = l * rs.rand(2, n_pts)
     66     mask[(points[0]).astype(np.int), (points[1]).astype(np.int)] = 1
     67     mask = ndimage.gaussian_filter(mask, sigma=l / n_pts)

mtrand.pyx in mtrand.RandomState.rand (numpy/random/mtrand/mtrand.c:19746)()

mtrand.pyx in mtrand.RandomState.random_sample (numpy/random/mtrand/mtrand.c:15541)()

mtrand.pyx in mtrand.cont0_array (numpy/random/mtrand/mtrand.c:6141)()

TypeError: 'float' object cannot be interpreted as an integer

**Comment by charlswart** [comment]
Had the same problem.  Seems that the n_pts variable is a float where an int is expected fixed by type casting.  Changed statement:
       points = l * rs.rand(2, n_pts)
To:
       points = l * rs.rand(2, int(n_pts))

**Comment by sachinruk** [comment]
Hey People,

Think I might close this off, I replaced that section with the link in scikit learn that I copied it all the code from. It's very much optional and distracts from where I want to go with Deep Learning. Cheers none the less.
