### ISSUE TITLE
xvfb-run error?

### ISSUE THREAD

**Issue by endofu** [sachinruk/deepschool.io#9]
I wanted to try the project and after running docker-compose http://0.0.0.0:8888 wasn't responding. I checked and there was no conflict of ports or so. 

Here's the build log from the terminal:
`Creating network "deepschoolio_default" with the default driver
Building app
Step 1/1 : FROM sachinruk/ml_class
latest: Pulling from sachinruk/ml_class
bd97b43c27e3: Pull complete
6960dc1aba18: Pull complete
2b61829b0db5: Pull complete
1f88dc826b14: Pull complete
73b3859b1e43: Pull complete
b5726da2badf: Pull complete
7246c11a4887: Pull complete
bd832a5f3d35: Pull complete
dd1dafb8acfd: Pull complete
8067dca54168: Pull complete
03add0ec109c: Pull complete
fdfb622e10f0: Pull complete
6bec0ed891da: Pull complete
08fd904fe6b7: Pull complete
Digest: sha256:33bda32be618ddcbe3f68340bbd13c019b2d089f2b23020f3d631d4aba4aa226
Status: Downloaded newer image for sachinruk/ml_class:latest
 ---> 9b7da273d8ec
Successfully built 9b7da273d8ec
Successfully tagged deepschoolio_app:latest
Creating deepschoolio_app_1 ...
Creating deepschoolio_app_1 ... done
Attaching to deepschoolio_app_1
app_1  | [I 10:42:02.883 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
app_1  | [W 10:42:02.932 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
app_1  | [I 10:42:02.944 NotebookApp] Serving notebooks from local directory: /notebook
app_1  | [I 10:42:02.945 NotebookApp] 0 active kernels
app_1  | [I 10:42:02.945 NotebookApp] The Jupyter Notebook is running at: http://0.0.0.0:8888/
app_1  | [I 10:42:02.946 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
^CGracefully stopping... (press Ctrl+C again to force)
Stopping deepschoolio_app_1 ... done`

Now when I try to 'up' the image again I get this: 
`Building app
Step 1/1 : FROM sachinruk/ml_class
 ---> 9b7da273d8ec
Successfully built 9b7da273d8ec
Successfully tagged deepschoolio_app:latest
Starting deepschoolio_app_1 ...
Starting deepschoolio_app_1 ... done
Attaching to deepschoolio_app_1
app_1  | xvfb-run: error: Xvfb failed to start
deepschoolio_app_1 exited with code 1`

Shouldn't matter I guess but I'm on Mac OS Sierra. Have any idea how to solve it or proofing the Dockerfile?

**Comment by sachinruk** [comment]
Pull the latest repo and try running `bash run.sh` now instead of `docker-compose up`. Had the issue myself. If not try running `docker run -d -p 9000:8888 -v ${PWD}:/notebook sachinruk/ml_class`

**Comment by endofu** [comment]
It worked now. Thank you.. Looking forward to go through the content!
